### ISSUE TITLE
Avram key regex support

### ISSUE THREAD

**Issue by cKlee** [gbv/format.gbv.de#20]
Avram should support key 'regex' to make validation more explicit. E.g.

```json
"subfields": {
                "0": {
                    "code": "0",
                    "label": "Änderungskennung und Datum (getrennt durch \":\")",
                    "repeatable": false,
                    "regex": "^\d{4}:((0[1-9]|[12]\d|3[01])-(0[1-9]|1[0-2])-[12]\d{3})$"
                },
                "t": {
                    "code": "t",
                    "label": "Uhrzeit HH:MM:SS",
                    "repeatable": false,
                    "regex": "^(?:(?:([01]?\d|2[0-3]):)?([0-5]?\d):)?([0-5]?\d)$"
                }
            }
```

**Comment by cKlee** [comment]
I was going to suggest to support keys like 'length', 'minlength' and 'maxlength' when I realized that the regex key could cope this, like:

```json
"regex": "^.{4,6}$"
```

(sub)field must have at least 4 characters and 6 at max.

**Comment by nichtich** [comment]
What regex syntax? JSON Schema [refers to](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.3.3) the "ECMA 262 regular expression dialect".

**Comment by cKlee** [comment]
I guess this is the obvious choice.

**Comment by cKlee** [comment]
key could also be named 'pattern'
