### ISSUE TITLE
Add FOLIO Inventory bibliographic format

### ISSUE THREAD

**Issue by hemmefelix** [gbv/format.gbv.de#45]
Would it be okay if I a add a page for https://docs.google.com/spreadsheets/d/1RCZyXUA5rK47wZqfFPbiRM0xnw8WnMCcmlttT7B3VlI/edit#gid=278827110 to https://format.gbv.de/application/bibliographic? The format and scheme is still under development but I think it could be useful to have it described at format.gbv.de.

**Comment by nichtich** [comment]
Thanks for the info! Is there a homepage, schema, archived publication or anything else more stable than a Google Document?
-- 
Jakob Voß via Android

**Comment by hemmefelix** [comment]
In deed, there is a wiki page about the [Inventory Metadata Beta Elements](https://wiki.folio.org/x/LYPc), but it is quiet outdated. There is an JSON schema for each Inventory entity on github, e.g. for the instance record (== bibliographic title data) https://github.com/folio-org/mod-inventory-storage/blob/master/ramls/instance.json.
