### ISSUE TITLE
Add KBART format

### ISSUE THREAD

**Issue by nichtich** [gbv/format.gbv.de#61]
See https://www.niso.org/standards-committees/kbart/kbart-frequently-asked-questions

**Comment by felixlohmeier** [comment]
See also https://service-wiki.hbz-nrw.de/pages/viewpage.action?pageId=470024321

**Comment by nichtich** [comment]
@felixlohmeier Danke, auf der offiziellen Seite such mensch sich ja dusselig. Von einem formalen Schema (siehe https://www.w3.org/TR/tabular-metadata/) ganz zu schweigen.
